import test from 'node:test';
import assert from 'node:assert/strict';
import { classifyCandidate,mergeOptions,normalizeGerman,optionsForHeadword,optionsForListedForms } from '../scripts/kaikki-resolver-lib.mjs';

test('normalizes German forms without destroying umlauts or ß',()=>{assert.equal(normalizeGerman('  HÄUSER  '),'häuser');assert.equal(normalizeGerman('Straße'),'straße');});
test('resolves an explicit German form-of entry and keeps its attested IPA',()=>{const entry={word:'Testbetriebes',lang_code:'de',pos:'noun',pos_title:'Deklinierte Form',senses:[{form_of:[{word:'Testbetrieb'}],tags:['form-of','genitive','singular']}],sounds:[{ipa:'[ˈtɛstbəˌtʁiːbəs]'}]},candidate={rank:1,surfaceForm:'Testbetriebes',normalizedForm:'testbetriebes'},result=classifyCandidate(candidate,optionsForHeadword(entry));assert.equal(result.status,'resolved');assert.equal(result.selected.lemma,'Testbetrieb');assert.equal(result.selected.pos,'noun');assert.deepEqual(result.selected.formFeatures.sort(),['genitive','singular']);assert.deepEqual(result.selected.candidateIpas,['ˈtɛstbəˌtʁiːbəs']);});
test('resolves a target through a lemma forms table without borrowing lemma IPA',()=>{const entry={word:'gehen',lang_code:'de',pos:'verb',senses:[{glosses:['sich fortbewegen']}],sounds:[{ipa:'[ˈɡeːən]'}],forms:[{form:'ging',tags:['past','singular']}]},listed=optionsForListedForms(entry,new Set(['ging'])),result=classifyCandidate({rank:2,surfaceForm:'ging',normalizedForm:'ging'},listed.map((x)=>x.option));assert.equal(result.status,'resolved');assert.equal(result.selected.lemma,'gehen');assert.deepEqual(result.selected.formFeatures.sort(),['past','singular']);assert.deepEqual(result.selected.candidateIpas,[]);});
test('marks a surface ambiguous when Wiktionary supports multiple lexical resolutions',()=>{const a={word:'Band',lang_code:'de',pos:'noun',etymology_number:1,senses:[{glosses:['Buch']}]},b={word:'Band',lang_code:'de',pos:'noun',etymology_number:2,senses:[{glosses:['Musikgruppe']}]},result=classifyCandidate({rank:3,surfaceForm:'Band',normalizedForm:'band'},[...optionsForHeadword(a),...optionsForHeadword(b)]);assert.equal(result.status,'ambiguous');assert.equal(result.options.length,2);});
test('marks a headword historical only when every direct sense is historical',()=>{const historical=optionsForHeadword({word:'Minne',lang_code:'de',pos:'noun',senses:[{tags:['archaic'],glosses:['historical sense']}],sounds:[{ipa:'[ˈmɪnə]'}]})[0];assert.equal(historical.historicalOnly,true);assert.ok(historical.styleTags.includes('archaic'));const mixed=optionsForHeadword({word:'Bank',lang_code:'de',pos:'noun',senses:[{tags:['archaic'],glosses:['old']},{glosses:['current']}]})[0];assert.equal(mixed.historicalOnly,false);});
test('dated form-of evidence is historical',()=>{const option=optionsForHeadword({word:'ward',lang_code:'de',pos:'verb',senses:[{tags:['form-of','dated'],form_of:[{word:'werden'}]}],sounds:[{ipa:'[vaːɐ̯t]'}]})[0];assert.equal(option.historicalOnly,true);assert.ok(option.styleTags.includes('dated'));});
test('current evidence wins when the same lexical resolution has mixed historical evidence',()=>{const historical=optionsForHeadword({word:'Mal',lang_code:'de',pos:'noun',senses:[{tags:['obsolete']}]})[0],current=optionsForHeadword({word:'Mal',lang_code:'de',pos:'noun',senses:[{glosses:['current']}]})[0],[merged]=mergeOptions([historical,current]);assert.equal(merged.historicalOnly,false);});
test('listed inflections inherit historical-only status from an exclusively historical lemma',()=>{const [listed]=optionsForListedForms({word:'Minne',lang_code:'de',pos:'noun',senses:[{tags:['archaic'],glosses:['old']}],forms:[{form:'Minnen',ipa:'[ˈmɪnən]'}]});assert.equal(listed.option.historicalOnly,true);assert.ok(listed.option.styleTags.includes('archaic'));const [mixed]=optionsForListedForms({word:'Bank',lang_code:'de',pos:'noun',senses:[{tags:['archaic']},{glosses:['current']}],forms:[{form:'Bänke'}]});assert.equal(mixed.option.historicalOnly,false);});
