const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

const PRIMARY_RHYME_TYPES = ['multisyllabic_perfect','perfect','multisyllabic_slant','family','slant'];
const SOUND_RELATION_TYPES = ['assonance','consonance'];
const RHYME_TYPES = [...PRIMARY_RHYME_TYPES, ...SOUND_RELATION_TYPES];

const I18N = {
  en: {
    title:'RhymeLab Local',eyebrow:'GERMAN RHYME ENGINE',headline:'Find rhymes by sound, not spelling.',
    intro:'Local phonetic search across German dictionary data, usage frequency and a curated modern vocabulary layer.',
    noteLocal:'Runs locally',notePhonetic:'IPA-based',noteUsage:'Usage-ranked',browse:'Browse results',rhymeType:'Rhyme / sound relation',
    syllables:'Syllables',sort:'Sort',pronunciation:'Pronunciation',vocabulary:'Vocabulary',all:'All',same:'Same count',plusMinus:'±1 syllable',
    recommended:'Recommended',mostCommon:'Most common',closest:'Closest rhyme',alphabetical:'A–Z',standard:'Standard',allVariants:'All variants',
    searching:'Searching…',includeHistorical:'Include historical / obsolete',scrollMore:'Scroll for more results…',searchPlaceholder:'Search a word…',search:'Search',
    noResults:'No matching rhymes for these filters.',result:'result',results:'results',syllableCount:'Syllables',primaryStress:'Primary stress',
    partOfSpeech:'Part of speech',lemma:'Lemma',usageRank:'Usage rank',corpusCount:'Corpus count',source:'Source',lexicalTags:'Lexical tags',
    variants:'Pronunciations',standardLabel:'Standard',alternate:'Alternate',unknown:'Unknown',unranked:'No usage rank',dictionary:'Dictionary',
    modern:'Modern lexicon',historical:'Historical',syllableShort:'syll.',modernEntity:'Modern',historicalEntity:'Historical',inspectWord:'Inspect',
    rhymeAnalysis:'Rhyme analysis',primaryRhyme:'Primary rhyme',soundRelations:'Sound relations',relationOnly:'Sound relation only',
    matchScore:'Primary rhyme score',vowelFit:'Vowel fit',codaFit:'Coda fit',stressFit:'Stress fit',syllableFit:'Syllable fit',
    consonanceFit:'Consonant fit',onsetFit:'Onset fit',relationStrong:'strong',relationPartial:'partial',
    type_multisyllabic_perfect:'Multisyllabic perfect',type_perfect:'Perfect rhyme',type_multisyllabic_slant:'Multisyllabic slant',
    type_family:'Rhyme family',type_slant:'Slant rhyme',type_assonance:'Assonance',type_consonance:'Consonance',type_weak:'No primary rhyme',
    notFound:'Word not found in the local rhyme database.',
  },
  de: {
    title:'RhymeLab Lokal',eyebrow:'DEUTSCHE REIM-ENGINE',headline:'Reime nach Klang, nicht nach Schreibweise.',
    intro:'Lokale phonetische Suche über deutsche Wörterbuchdaten, Gebrauchshäufigkeit und ein kuratiertes modernes Vokabular.',
    noteLocal:'Läuft lokal',notePhonetic:'IPA-basiert',noteUsage:'Nach Gebrauch sortiert',browse:'Ergebnisse durchsuchen',rhymeType:'Reim / Klangbeziehung',
    syllables:'Silben',sort:'Sortierung',pronunciation:'Aussprache',vocabulary:'Wortschatz',all:'Alle',same:'Gleiche Anzahl',plusMinus:'±1 Silbe',
    recommended:'Empfohlen',mostCommon:'Am häufigsten',closest:'Ähnlichster Reim',alphabetical:'A–Z',standard:'Standard',allVariants:'Alle Varianten',
    searching:'Suche…',includeHistorical:'Historische / veraltete einbeziehen',scrollMore:'Weiter scrollen für mehr Ergebnisse…',searchPlaceholder:'Wort suchen…',search:'Suchen',
    noResults:'Keine passenden Reime für diese Filter.',result:'Ergebnis',results:'Ergebnisse',syllableCount:'Silben',primaryStress:'Hauptbetonung',
    partOfSpeech:'Wortart',lemma:'Lemma',usageRank:'Gebrauchsrang',corpusCount:'Korpus-Treffer',source:'Quelle',lexicalTags:'Lexikalische Tags',
    variants:'Aussprachen',standardLabel:'Standard',alternate:'Variante',unknown:'Unbekannt',unranked:'Kein Gebrauchsrang',dictionary:'Wörterbuch',
    modern:'Modernes Lexikon',historical:'Historisch',syllableShort:'Silb.',modernEntity:'Modern',historicalEntity:'Historisch',inspectWord:'Details zu',
    rhymeAnalysis:'Reimanalyse',primaryRhyme:'Primärreim',soundRelations:'Klangbeziehungen',relationOnly:'Nur Klangbeziehung',
    matchScore:'Primärreim-Wert',vowelFit:'Vokal-Übereinstimmung',codaFit:'Endrand-Übereinstimmung',stressFit:'Betonungs-Übereinstimmung',
    syllableFit:'Silben-Übereinstimmung',consonanceFit:'Konsonanten-Übereinstimmung',onsetFit:'Anlaut-Übereinstimmung',relationStrong:'stark',relationPartial:'partiell',
    type_multisyllabic_perfect:'Mehrsilbiger Vollreim',type_perfect:'Vollreim',type_multisyllabic_slant:'Mehrsilbiger Slant-Reim',
    type_family:'Reimfamilie',type_slant:'Slant-Reim',type_assonance:'Assonanz',type_consonance:'Konsonanz',type_weak:'Kein Primärreim',
    notFound:'Wort nicht in der lokalen Reimdatenbank gefunden.',
  },
};

const LEXICAL_TAG_LABELS = {
  en:{slang:'Slang',colloquial:'Colloquial',informal:'Informal',vulgar:'Vulgar',offensive:'Offensive',derogatory:'Derogatory',archaic:'Archaic',obsolete:'Obsolete',dated:'Dated',rare:'Rare',regional:'Regional',dialectal:'Dialectal',poetic:'Poetic'},
  de:{slang:'Slang',colloquial:'Umgangssprachlich',informal:'Informell',vulgar:'Vulgär',offensive:'Anstößig',derogatory:'Abwertend',archaic:'Archaisch',obsolete:'Veraltet',dated:'Überholt / veraltet',rare:'Selten',regional:'Regional',dialectal:'Dialektal',poetic:'Poetisch'},
};
const POS_LABELS = {
  en:{noun:'Noun',verb:'Verb',adj:'Adjective',adjective:'Adjective',adv:'Adverb',adverb:'Adverb',name:'Proper name',proper_noun:'Proper noun',pron:'Pronoun',pronoun:'Pronoun',det:'Determiner',determiner:'Determiner',prep:'Preposition',preposition:'Preposition',conj:'Conjunction',conjunction:'Conjunction',interj:'Interjection',interjection:'Interjection',num:'Numeral',numeral:'Numeral',particle:'Particle',article:'Article',prefix:'Prefix',suffix:'Suffix',phrase:'Phrase',abbrev:'Abbreviation',abbreviation:'Abbreviation'},
  de:{noun:'Substantiv',verb:'Verb',adj:'Adjektiv',adjective:'Adjektiv',adv:'Adverb',adverb:'Adverb',name:'Eigenname',proper_noun:'Eigenname',pron:'Pronomen',pronoun:'Pronomen',det:'Determinierer',determiner:'Determinierer',prep:'Präposition',preposition:'Präposition',conj:'Konjunktion',conjunction:'Konjunktion',interj:'Interjektion',interjection:'Interjektion',num:'Numerale',numeral:'Numerale',particle:'Partikel',article:'Artikel',prefix:'Präfix',suffix:'Suffix',phrase:'Phrase',abbrev:'Abkürzung',abbreviation:'Abkürzung'},
};
const ENTITY_LABELS={en:{platform:'Platform',company:'Company',product:'Product',internet:'Internet term',entity:'Entity'},de:{platform:'Plattform',company:'Unternehmen',product:'Produkt',internet:'Internetbegriff',entity:'Entität'}};

const state={lang:localStorage.getItem('rhymelab.language')==='de'?'de':'en',data:null,visibleCount:30,pageSize:30,query:'',scrollObserver:null,wordCache:new Map(),detailRequest:0,inspectedWord:null,inspectedResult:null,inspectedType:null};
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(key)=>I18N[state.lang][key]??I18N.en[key]??key;
const number=(value)=>Number(value).toLocaleString(state.lang==='de'?'de-DE':'en-US');
const normalizeKey=(value)=>String(value??'').normalize('NFKC').trim().toLocaleLowerCase('de-DE');

function humanize(value){return String(value??'').replace(/^wiktionary:/,'').replaceAll('_',' ').replaceAll('-',' ').replace(/\b\p{L}/gu,(char)=>char.toLocaleUpperCase(state.lang==='de'?'de-DE':'en-US'));}
function lexicalTagLabel(tag){return LEXICAL_TAG_LABELS[state.lang]?.[tag]??LEXICAL_TAG_LABELS.en[tag]??humanize(tag);}
function partOfSpeechLabel(value){if(!value)return null;return POS_LABELS[state.lang]?.[value]??POS_LABELS.en[value]??humanize(value);}
function entityLabel(value){if(!value)return null;return ENTITY_LABELS[state.lang]?.[value]??ENTITY_LABELS.en[value]??humanize(value);}
function sourceLabel(value){const source=String(value??'').trim();if(!source)return'—';const normalized=source.toLocaleLowerCase('en-US');if(normalized.includes('wiktionary')&&normalized.includes('kaikki')){const english=normalized.includes('english');if(state.lang==='de')return english?'Englisches Wiktionary via Kaikki/Wiktextract':'Deutsches Wiktionary via Kaikki/Wiktextract';return english?'English Wiktionary via Kaikki/Wiktextract':'German Wiktionary via Kaikki/Wiktextract';}if(normalized.includes('rhymelab curated modern lexicon'))return state.lang==='de'?'RhymeLab – kuratiertes modernes Lexikon':'RhymeLab curated modern lexicon';return source;}
function localeLabel(value){const maps={de:{'de-DE':'Deutsch (Deutschland)','de-AT':'Deutsch (Österreich)','de-CH':'Deutsch (Schweiz)','en-US':'Englisch (USA)','en-GB':'Englisch (Großbritannien)','en-CA':'Englisch (Kanada)','en-AU':'Englisch (Australien)'},en:{'de-DE':'German (Germany)','de-AT':'German (Austria)','de-CH':'German (Switzerland)','en-US':'English (United States)','en-GB':'English (United Kingdom)','en-CA':'English (Canada)','en-AU':'English (Australia)'}};return maps[state.lang]?.[value]??value;}
function dialectLabel(value){const map=state.lang==='de'?{'Austrian German':'Österreichisches Deutsch','Swiss German':'Schweizerdeutsch','General American':'General American','Received Pronunciation':'Received Pronunciation'}:{'Austrian German':'Austrian German','Swiss German':'Swiss German','General American':'General American','Received Pronunciation':'Received Pronunciation'};return map[value]??value;}
function registerLabel(value){const map=state.lang==='de'?{colloquial:'Umgangssprachlich'}:{colloquial:'Colloquial'};return map[value]??humanize(value);}
function typeLabel(type){return t(`type_${type}`);}
function relationFor(row,type){return(row.relations||[]).find((relation)=>relation.type===type)||null;}
function rowTypes(row){const types=new Set();if(row.primaryType&&PRIMARY_RHYME_TYPES.includes(row.primaryType))types.add(row.primaryType);else if(PRIMARY_RHYME_TYPES.includes(row.type))types.add(row.type);for(const type of row.relationTypes||[])if(SOUND_RELATION_TYPES.includes(type))types.add(type);return RHYME_TYPES.filter((type)=>types.has(type));}
function matchesType(row,type){return rowTypes(row).includes(type);}
function displayScore(row,type){return SOUND_RELATION_TYPES.includes(type)?Number(relationFor(row,type)?.score||0):Number(row.score||0);}

function applyLanguage(){document.documentElement.lang=state.lang;document.title=t('title');$('#searchInput').placeholder=t('searchPlaceholder');$('#searchInput').setAttribute('aria-label',t('searchPlaceholder'));$('#searchButton').textContent=t('search');$$('[data-i18n]').forEach((node)=>{node.textContent=t(node.dataset.i18n);});$$('[data-i18n-option]').forEach((node)=>{node.textContent=t(node.dataset.i18nOption);});$$('.lang-option').forEach((button)=>button.classList.toggle('active',button.dataset.lang===state.lang));if(state.data)render();}
function compareRecommended(a,b){if(Number.isFinite(a.writerRank)&&Number.isFinite(b.writerRank))return a.writerRank-b.writerRank;return a.rhymeTier-b.rhymeTier||a.syllableDistance-b.syllableDistance||(a.usageRank==null)-(b.usageRank==null)||(a.usageRank??Number.MAX_SAFE_INTEGER)-(b.usageRank??Number.MAX_SAFE_INTEGER)||b.score-a.score||a.word.localeCompare(b.word,state.data?.language==='en'?'en':'de');}
function compareForDisplayType(a,b,type){if(SOUND_RELATION_TYPES.includes(type)){const ar=relationFor(a,type),br=relationFor(b,type);return(Number(ar?.strength!=='strong')-Number(br?.strength!=='strong'))||displayScore(b,type)-displayScore(a,type)||a.syllableDistance-b.syllableDistance||(a.usageRank==null)-(b.usageRank==null)||(a.usageRank??Number.MAX_SAFE_INTEGER)-(b.usageRank??Number.MAX_SAFE_INTEGER)||b.score-a.score;}return compareRecommended(a,b);}
function filteredResults(){if(!state.data)return[];const querySyllables=Number(state.data.query?.syllableCount||0),type=$('#typeFilter').value,syllable=$('#syllableFilter').value;let rows=state.data.results.filter((row)=>{if(type!=='all'&&!matchesType(row,type))return false;const distance=Math.abs(Number(row.syllableCount||0)-querySyllables);if(syllable==='same'&&distance!==0)return false;if(syllable==='near'&&distance>1)return false;return true;});const mode=$('#sortMode').value;rows=[...rows].sort((a,b)=>{if(type!=='all'&&mode==='recommended')return compareForDisplayType(a,b,type);if(mode==='common')return(a.usageRank==null)-(b.usageRank==null)||(a.usageRank??Number.MAX_SAFE_INTEGER)-(b.usageRank??Number.MAX_SAFE_INTEGER)||a.rhymeTier-b.rhymeTier||a.syllableDistance-b.syllableDistance||b.score-a.score;if(mode==='closest')return(type!=='all'?displayScore(b,type)-displayScore(a,type):b.score-a.score)||a.rhymeTier-b.rhymeTier||a.syllableDistance-b.syllableDistance||(a.usageRank==null)-(b.usageRank==null)||(a.usageRank??Number.MAX_SAFE_INTEGER)-(b.usageRank??Number.MAX_SAFE_INTEGER);if(mode==='alpha')return a.word.localeCompare(b.word,state.data?.language==='en'?'en':'de',{sensitivity:'base'});return compareRecommended(a,b);});return rows;}
function interleaveByType(rows){if(state.data?.rankingPolicy==='deterministic_writer_utility_v1')return rows;if($('#typeFilter').value!=='all')return rows;const buckets=RHYME_TYPES.map((type)=>rows.filter((row)=>matchesType(row,type)).sort((a,b)=>compareForDisplayType(a,b,type))).filter((bucket)=>bucket.length);if(buckets.length<=1)return rows;const output=[],seen=new Set();for(let index=0;output.length<rows.length;index+=1){let added=false;for(const bucket of buckets){const row=bucket[index];if(row&&!seen.has(row.normalized)){seen.add(row.normalized);output.push(row);added=true;}}if(!added&&buckets.every((bucket)=>index>=bucket.length))break;}for(const row of rows)if(!seen.has(row.normalized)){seen.add(row.normalized);output.push(row);}return output;}
function rhymeAnalysisHtml(result,displayType=null){if(!result)return'';const component=(key,label)=>{const value=result.components?.[key];if(value==null)return'';return`<div class="analysis-metric"><span>${label}</span><strong>${Math.round(value*100)}%</strong></div>`;};const primary=result.primaryType||((PRIMARY_RHYME_TYPES.includes(result.type))?result.type:null);const relations=(result.relations||[]).map((relation)=>`<span class="badge ${esc(relation.type)}${displayType===relation.type?' active-relation':''}">${esc(typeLabel(relation.type))} · ${esc(t(relation.strength==='strong'?'relationStrong':'relationPartial'))} · ${Math.round(relation.score*100)}%</span>`).join('');return`<div class="rhyme-analysis"><h3>${t('rhymeAnalysis')}</h3><div class="analysis-summary"><div><span class="meta-label">${t('primaryRhyme')}</span><strong>${esc(primary?typeLabel(primary):t('relationOnly'))}</strong></div><div><span class="meta-label">${t('matchScore')}</span><strong>${primary?`${Math.round(result.score*100)}%`:'—'}</strong></div></div>${relations?`<div class="relation-summary"><span class="meta-label">${t('soundRelations')}</span><div>${relations}</div></div>`:''}<div class="analysis-grid">${component('vowel',t('vowelFit'))}${component('coda',t('codaFit'))}${component('stress',t('stressFit'))}${component('syllable',t('syllableFit'))}${component('consonance',t('consonanceFit'))}${component('onset',t('onsetFit'))}</div></div>`;}
function renderWordPanel(query,rhymeResult=null,displayType=null){const pronunciations=query.pronunciations||[],preferred=pronunciations.find((p)=>p.preferred)||pronunciations[0],layer=query.lexiconLayer==='modern'?t('modern'):t('dictionary');const pronunciationHtml=pronunciations.slice(0,8).map((p)=>{const detail=[p.preferred?t('standardLabel'):t('alternate'),p.locale?localeLabel(p.locale):null,p.register?registerLabel(p.register):null,p.dialect?dialectLabel(p.dialect):null].filter(Boolean).join(' · ');return`<div class="pronunciation-item"><code>/${esc(p.ipa)}/</code><small>${esc(detail)}</small></div>`;}).join('');const tags=Array.isArray(query.lexicalTags)?query.lexicalTags:[],tagHtml=tags.length?`<div class="lexical-tags"><span class="meta-label">${t('lexicalTags')}</span><div>${tags.map((tag)=>`<span title="${esc(tag)}">${esc(lexicalTagLabel(tag))}</span>`).join('')}</div></div>`:'',source=sourceLabel(preferred?.source),grammaticalLabel=partOfSpeechLabel(query.partOfSpeech)||entityLabel(query.entityKind)||'—';$('#wordPanel').innerHTML=`<div class="word-heading"><div><h2>${esc(query.surface)}</h2><div class="ipa">/${esc(query.preferredIpa||preferred?.ipa||'')}/</div></div><div class="layer-badges"><span class="layer-badge ${query.lexiconLayer==='modern'?'modern':''}">${esc(layer)}</span>${query.historical?`<span class="layer-badge historical">${t('historical')}</span>`:''}</div></div><div class="meta-grid"><div class="meta-item"><span class="meta-label">${t('syllableCount')}</span><span class="meta-value">${esc(query.syllableCount??t('unknown'))}</span></div><div class="meta-item"><span class="meta-label">${t('primaryStress')}</span><span class="meta-value">${esc(query.primaryStressSyllable??t('unknown'))}</span></div><div class="meta-item"><span class="meta-label">${t('usageRank')}</span><span class="meta-value">${query.usageRank?`#${number(query.usageRank)}`:t('unranked')}</span></div><div class="meta-item"><span class="meta-label">${t('corpusCount')}</span><span class="meta-value">${query.usageCount!=null?number(query.usageCount):'—'}</span></div><div class="meta-item"><span class="meta-label">${t('partOfSpeech')}</span><span class="meta-value">${esc(grammaticalLabel)}</span></div><div class="meta-item"><span class="meta-label">${t('lemma')}</span><span class="meta-value">${esc(query.lemma||'—')}</span></div><div class="meta-item meta-wide"><span class="meta-label">${t('source')}</span><span class="meta-value source-value">${esc(source)}</span></div></div>${rhymeAnalysisHtml(rhymeResult,displayType)}${tagHtml}<div class="pronunciation-list"><h3>${t('variants')}</h3>${pronunciationHtml||'—'}</div>`;}
function resultRow(row,displayType){const usage=row.usageRank?`#${number(row.usageRank)}`:'—',usageSub=row.usageCount!=null?number(row.usageCount):t('unranked'),score=displayScore(row,displayType);return`<div class="result-row" data-normalized="${esc(row.normalized)}" data-display-type="${esc(displayType)}" tabindex="0" aria-label="${esc(`${t('inspectWord')} ${row.word}`)}"><div class="result-word"><strong>${esc(row.word)}</strong><div class="sub"><code>/${esc(row.ipa)}/</code>${row.lexiconLayer==='modern'?`<span>${t('modernEntity')}</span>`:''}${row.historical?`<span class="historical-text">${t('historicalEntity')}</span>`:''}</div></div><div class="type-col"><span class="badge ${esc(displayType)}">${esc(typeLabel(displayType))}</span></div><div class="syllable-col metric">${esc(row.syllableCount)}<span class="muted">${t('syllableShort')}</span></div><div class="usage-col metric">${usage}<span class="muted">${esc(usageSub)}</span></div><div class="score">${Math.round(score*100)}%</div></div>`;}
function section(type,rows,totalCount){return`<section class="result-section ${esc(type)}"><div class="result-section-header"><span class="type-dot"></span><h2>${esc(typeLabel(type))}</h2><span class="count">${totalCount}</span></div>${rows.map((row)=>resultRow(row,type)).join('')}</section>`;}
function setupInfiniteScroll(hasMore){state.scrollObserver?.disconnect();state.scrollObserver=null;const sentinel=$('#scrollSentinel');sentinel.classList.toggle('hidden',!hasMore);if(!hasMore)return;if(!('IntersectionObserver'in window)){state.visibleCount=Number.MAX_SAFE_INTEGER;render();return;}state.scrollObserver=new IntersectionObserver((entries)=>{if(!entries.some((entry)=>entry.isIntersecting))return;state.visibleCount+=state.pageSize;render();},{rootMargin:'500px 0px'});state.scrollObserver.observe(sentinel);}
function render(){if(!state.data)return;if(!state.inspectedWord)renderWordPanel(state.data.query);const rows=filteredResults(),ordered=interleaveByType(rows),visibleRows=ordered.slice(0,state.visibleCount);$('#resultCount').textContent=`${number(rows.length)} ${rows.length===1?t('result'):t('results')}`;if(!visibleRows.length)$('#results').innerHTML=`<div class="status">${t('noResults')}</div>`;else $('#results').innerHTML=RHYME_TYPES.map((type)=>{const items=visibleRows.filter((row)=>matchesType(row,type)),totalCount=rows.filter((row)=>matchesType(row,type)).length;return items.length?section(type,items,totalCount):'';}).join('');setupInfiniteScroll(visibleRows.length<rows.length);}
function resultByNormalized(normalized){return state.data?.results?.find((row)=>row.normalized===normalized)||null;}
async function inspectResult(result,displayType=null){if(!result)return;const key=normalizeKey(result.normalized||result.word);if(!key||!state.data)return;state.inspectedWord=key;state.inspectedResult=result;state.inspectedType=displayType;const token=++state.detailRequest,cached=state.wordCache.get(key);if(cached){if(token===state.detailRequest&&state.inspectedWord===key)renderWordPanel(cached,result,displayType);return;}try{const response=await fetch(`/api/word/${encodeURIComponent(result.word)}`);if(!response.ok)return;const detail=await response.json();state.wordCache.set(key,detail);if(token===state.detailRequest&&state.inspectedWord===key)renderWordPanel(detail,result,displayType);}catch{}}
function restoreQueryPanel(){state.inspectedWord=null;state.inspectedResult=null;state.inspectedType=null;state.detailRequest+=1;if(state.data?.query)renderWordPanel(state.data.query);}

async function search(word){state.query=word.trim();if(!state.query)return;$('#emptyState').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#loading').classList.remove('hidden');$('#error').classList.add('hidden');$('#results').innerHTML='';state.visibleCount=state.pageSize;state.inspectedWord=null;state.inspectedResult=null;state.inspectedType=null;state.detailRequest+=1;state.scrollObserver?.disconnect();try{const requestedType=$('#typeFilter').value,params=new URLSearchParams({limit:'250',pool:'800',variants:$('#variantMode').value,historical:$('#historicalMode').checked?'all':'current',type:requestedType,coverage:requestedType==='all'?'balanced':'ranked',coverage_floor:'20',ranking:'writer'}),response=await fetch(`/api/rhymes/${encodeURIComponent(state.query)}?${params}`),data=await response.json();if(!response.ok)throw new Error(response.status===404?t('notFound'):(data.error||'Request failed'));state.data=data;state.wordCache.set(normalizeKey(data.query?.surface||state.query),data.query);const url=new URL(location.href);url.searchParams.set('q',state.query);history.replaceState(null,'',url);render();}catch(error){state.data=null;$('#wordPanel').innerHTML='';$('#scrollSentinel').classList.add('hidden');$('#error').textContent=error.message;$('#error').classList.remove('hidden');}finally{$('#loading').classList.add('hidden');}}

$('#searchForm').addEventListener('submit',(event)=>{event.preventDefault();search($('#searchInput').value);});
$$('.lang-option').forEach((button)=>button.addEventListener('click',()=>{state.lang=button.dataset.lang==='de'?'de':'en';localStorage.setItem('rhymelab.language',state.lang);applyLanguage();}));
$('#typeFilter').addEventListener('change',()=>{if(state.query)search(state.query);});
['syllableFilter','sortMode'].forEach((id)=>$(`#${id}`).addEventListener('change',()=>{state.visibleCount=state.pageSize;render();}));
$('#variantMode').addEventListener('change',()=>{if(state.query)search(state.query);});
$('#historicalMode').addEventListener('change',()=>{if(state.query)search(state.query);});
$('#results').addEventListener('pointerover',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;inspectResult(resultByNormalized(row.dataset.normalized),row.dataset.displayType);});
$('#results').addEventListener('pointerout',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;restoreQueryPanel();});
$('#results').addEventListener('focusin',(event)=>{const row=event.target.closest('.result-row');if(row)inspectResult(resultByNormalized(row.dataset.normalized),row.dataset.displayType);});
$('#results').addEventListener('focusout',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;restoreQueryPanel();});
applyLanguage();
const initial=new URL(location.href).searchParams.get('q');
if(initial){$('#searchInput').value=initial;search(initial);}
