const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

const PRIMARY_RHYME_TYPES = ['multisyllabic_perfect','perfect','multisyllabic_slant','family','slant'];
const SOUND_RELATION_TYPES = ['assonance','consonance'];
const RHYME_TYPES = [...PRIMARY_RHYME_TYPES, ...SOUND_RELATION_TYPES];

const I18N = {
  en: {
    title:'RhymeLab Local',eyebrow:'GERMAN RHYME ENGINE',headline:'Find rhymes by sound, not spelling.',
    intro:'One local phonetic workspace for single-word rhymes and cross-word Phrase/Mosaic matches.',
    noteLocal:'Runs locally',notePhonetic:'IPA-based',noteUsage:'Deterministic',browse:'Browse results',resultScope:'Results',scopeAll:'Words + phrases',scopeWords:'Words',scopePhrases:'Phrases / Mosaic',words:'Words',phrases:'Phrases / Mosaic',word:'Word',phrase:'Phrase',rhymeType:'Rhyme / sound relation',
    syllables:'Syllables',sort:'Sort',pronunciation:'Pronunciation',vocabulary:'Vocabulary',all:'All',same:'Same count',plusMinus:'±1 syllable',
    recommended:'Recommended',mostCommon:'Most common',closest:'Closest rhyme',alphabetical:'A–Z',standard:'Standard',allVariants:'All variants',
    searching:'Searching…',includeHistorical:'Include historical / obsolete words',scrollMore:'',searchPlaceholder:'Search a word or phrase…',search:'Search',
    noResults:'No matching rhymes for these filters.',result:'result',results:'results',syllableCount:'Syllables',primaryStress:'Primary stress',
    partOfSpeech:'Part of speech',lemma:'Lemma',usageRank:'Usage rank',corpusCount:'Corpus count',source:'Source',lexicalTags:'Lexical tags',
    variants:'Pronunciations',standardLabel:'Standard',alternate:'Alternate',unknown:'Unknown',unranked:'No usage rank',dictionary:'Dictionary',
    modern:'Modern lexicon',historical:'Historical',syllableShort:'syll.',modernEntity:'Modern',historicalEntity:'Historical',inspectWord:'Inspect',
    rhymeAnalysis:'Rhyme analysis',primaryRhyme:'Primary rhyme',soundRelations:'Sound relations',relationOnly:'Sound relation only',
    matchScore:'Primary rhyme score',vowelFit:'Vowel fit',codaFit:'Coda fit',stressFit:'Stress fit',syllableFit:'Syllable fit',
    consonanceFit:'Consonant fit',onsetFit:'Onset fit',relationStrong:'strong',relationPartial:'partial',
    type_multisyllabic_perfect:'Multisyllabic perfect',type_perfect:'Perfect rhyme',type_multisyllabic_slant:'Multisyllabic slant',
    type_family:'Rhyme family',type_slant:'Slant rhyme',type_assonance:'Assonance',type_consonance:'Consonance',type_weak:'No primary rhyme',
    notFound:'Word or phrase not found / not fully pronounceable from the local inventories.',englishUnavailable:'English runtime is not installed yet. The unified EN contract is ready, but no accepted English phonology/database exists yet.',bothPartial:'DE+EN selected: German is active; English will join this same Writer UI when its local runtime is installed.',
  },
  de: {
    title:'RhymeLab Lokal',eyebrow:'VEREINHEITLICHTER REIM-WRITER',headline:'Wörter und Wortgruppen nach Klang suchen.',
    intro:'Eine lokale phonetische Oberfläche für Einzelwort-Reime und wortübergreifende Phrase/Mosaic-Treffer.',
    noteLocal:'Läuft lokal',notePhonetic:'IPA-basiert',noteUsage:'Deterministisch',browse:'Ergebnisse',resultScope:'Ergebnisse',scopeAll:'Wörter + Wortgruppen',scopeWords:'Wörter',scopePhrases:'Wortgruppen / Mosaic',words:'Wörter',phrases:'Wortgruppen / Mosaic',word:'Wort',phrase:'Wortgruppe',rhymeType:'Reim / Klangbeziehung',
    syllables:'Silben',sort:'Sortierung',pronunciation:'Aussprache',vocabulary:'Wortschatz',all:'Alle',same:'Gleiche Anzahl',plusMinus:'±1 Silbe',
    recommended:'Empfohlen',mostCommon:'Am häufigsten',closest:'Ähnlichster Reim',alphabetical:'A–Z',standard:'Standard',allVariants:'Alle Varianten',
    searching:'Suche…',includeHistorical:'Historische / veraltete Wörter einbeziehen',scrollMore:'',searchPlaceholder:'Wort oder Wortgruppe suchen…',search:'Suchen',
    noResults:'Keine passenden Reime für diese Filter.',result:'Ergebnis',results:'Ergebnisse',syllableCount:'Silben',primaryStress:'Hauptbetonung',
    partOfSpeech:'Wortart',lemma:'Lemma',usageRank:'Gebrauchsrang',corpusCount:'Korpus-Treffer',source:'Quelle',lexicalTags:'Lexikalische Tags',
    variants:'Aussprachen',standardLabel:'Standard',alternate:'Variante',unknown:'Unbekannt',unranked:'Kein Gebrauchsrang',dictionary:'Wörterbuch',
    modern:'Modernes Lexikon',historical:'Historisch',syllableShort:'Silb.',modernEntity:'Modern',historicalEntity:'Historisch',inspectWord:'Details zu',
    rhymeAnalysis:'Reimanalyse',primaryRhyme:'Primärreim',soundRelations:'Klangbeziehungen',relationOnly:'Nur Klangbeziehung',
    matchScore:'Primärreim-Wert',vowelFit:'Vokal-Übereinstimmung',codaFit:'Endrand-Übereinstimmung',stressFit:'Betonungs-Übereinstimmung',
    syllableFit:'Silben-Übereinstimmung',consonanceFit:'Konsonanten-Übereinstimmung',onsetFit:'Anlaut-Übereinstimmung',relationStrong:'stark',relationPartial:'partiell',
    type_multisyllabic_perfect:'Mehrsilbiger Vollreim',type_perfect:'Vollreim',type_multisyllabic_slant:'Mehrsilbiger Slant-Reim',
    type_family:'Reimfamilie',type_slant:'Slant-Reim',type_assonance:'Assonanz',type_consonance:'Konsonanz',type_weak:'Kein Primärreim',
    notFound:'Wort oder Wortgruppe nicht gefunden bzw. nicht vollständig aus den lokalen Aussprachebeständen auflösbar.',englishUnavailable:'Die englische Runtime ist noch nicht installiert. Der gemeinsame EN-Contract ist vorbereitet, aber es gibt noch keine akzeptierte englische Phonologie/Datenbank.',bothPartial:'DE+EN ist gewählt: Deutsch ist aktiv; Englisch wird in dieselbe Writer-UI eingehängt, sobald die lokale EN-Runtime vorhanden ist.',
  },
};

const LEXICAL_TAG_LABELS = {
  en:{slang:'Slang',colloquial:'Colloquial',informal:'Informal',vulgar:'Vulgar',offensive:'Offensive',derogatory:'Derogatory',archaic:'Archaic',obsolete:'Obsolete',dated:'Dated',rare:'Rare',regional:'Regional',dialectal:'Dialectal',poetic:'Poetic'},
  de:{slang:'Slang',colloquial:'Umgangssprachlich',informal:'Informell',vulgar:'Vulgär',offensive:'Anstößig',derogatory:'Abwertend',archaic:'Archaisch',obsolete:'Veraltet',dated:'Überholt / veraltet',rare:'Selten',regional:'Regional',dialectal:'Dialektal',poetic:'Poetisch'},
};
const POS_LABELS = {
  en:{noun:'Noun',verb:'Verb',adj:'Adjective',adjective:'Adjective',adv:'Adverb',adverb:'Adverb',name:'Proper name',proper_noun:'Proper noun',pron:'Pronoun',pronoun:'Pronoun',det:'Determiner',determiner:'Determiner',prep:'Preposition',preposition:'Preposition',conj:'Conjunction',conjunction:'Conjunction',interj:'Interjection',interjection:'Interjection',num:'Numeral',numeral:'Numeral',particle:'Particle',article:'Article',prefix:'Prefix',suffix:'Suffix',phrase:'Phrase',abbrev:'Abbreviation',abbreviation:'Abbreviation'},
  de:{noun:'Substantiv',verb:'Verb',adj:'Adjektiv',adjective:'Adjektiv',adv:'Adverb',adverb:'Adverb',name:'Eigenname',proper_noun:'Eigenname',pron:'Pronomen',pronoun:'Pronomen',det:'Determinierer',determiner:'Determinierer',prep:'Präposition',preposition:'Präposition',conj:'Konjunktion',conjunction:'Konjunktion',interj:'Interjektion',interjection:'Interjektion',num:'Numerale',numeral:'Numerale',particle:'Partikel',article:'Artikel',prefix:'Präfix',suffix:'Suffix',phrase:'Phrase',abbrev:'Abkürzung',abbreviation:'Abkürzung'},
};
const ENTITY_LABELS={en:{platform:'Platform',company:'Company',product:'Product',internet:'Internet term',entity:'Entity'},de:{platform:'Plattform',company:'Unternehmen',product:'Produkt',internet:'Internetbegriff',entity:'Entität'}};

const savedBasis=localStorage.getItem('rhymelab.searchBasis');const state={lang:localStorage.getItem('rhymelab.language')==='de'?'de':'en',basis:['de','en','both'].includes(savedBasis)?savedBasis:'de',capabilities:null,data:null,visibleCount:500,pageSize:500,query:'',scrollObserver:null,wordCache:new Map(),detailRequest:0,inspectedWord:null,inspectedResult:null,inspectedType:null};
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(key)=>I18N[state.lang][key]??I18N.en[key]??key;
const number=(value)=>Number(value).toLocaleString(state.lang==='de'?'de-DE':'en-US');
const normalizeKey=(value)=>String(value??'').normalize('NFKC').trim().toLocaleLowerCase('de-DE');

function humanize(value){return String(value??'').replace(/^wiktionary:/,'').replaceAll('_',' ').replaceAll('-',' ').replace(/\b\p{L}/gu,(char)=>char.toLocaleUpperCase(state.lang==='de'?'de-DE':'en-US'));}
function lexicalTagLabel(tag){return LEXICAL_TAG_LABELS[state.lang]?.[tag]??LEXICAL_TAG_LABELS.en[tag]??humanize(tag);}
function partOfSpeechLabel(value){if(!value)return null;return POS_LABELS[state.lang]?.[value]??POS_LABELS.en[value]??humanize(value);}
function entityLabel(value){if(!value)return null;return ENTITY_LABELS[state.lang]?.[value]??ENTITY_LABELS.en[value]??humanize(value);}
function sourceLabel(value){const source=String(value??'').trim();if(!source)return'—';const normalized=source.toLocaleLowerCase('en-US');if(normalized.includes('wiktionary')&&normalized.includes('kaikki')){const english=normalized.includes('english');if(state.lang==='de')return english?'Englisches Wiktionary via Kaikki/Wiktextract':'Deutsches Wiktionary via Kaikki/Wiktextract';return english?'English Wiktionary via Kaikki/Wiktextract':'German Wiktionary via Kaikki/Wiktextract';}if(normalized.includes('rhymelab curated modern lexicon'))return state.lang==='de'?'RhymeLab – kuratiertes modernes Lexikon':'RhymeLab curated modern lexicon';return source;}
function localeLabel(value){const maps={de:{'de-DE':'Deutsch (Deutschland)','de-AT':'Deutsch (Österreich)','de-CH':'Deutsch (Schweiz)','en-US':'Englisch (USA)','en-GB':'Englisch (Großbritannien)','en-CA':'Englisch (Kanada)','en-AU':'Englisch (Australien)'},en:{'de-DE':'German (Germany)','de-AT':'German (Austria)','de-CH':'German (Switzerland)','en-US':'English (United States)','en-GB':'English (United Kingdom)','en-CA':'English (Canada)','en-AU':'English (Australia)'}};return maps[state.lang]?.[value]??value;}
function dialectLabel(value){const map=state.lang==='de'?{'Austrian German':'Österreichisches Deutsch','Swiss German':'Schweizerdeutsch','General American':'General American','Received Pronunciation':'Received Pronunciation'}:{'Austrian German':'Austrian German','Swiss German':'Swiss German','General American':'General American','Received Pronunciation':'Received Pronunciation'};return map[value]??value;}
function registerLabel(value){const map=state.lang==='de'?{colloquial:'Umgangssprachlich'}:{colloquial:'Colloquial'};return map[value]??humanize(value);}
function typeLabel(type){return t(`type_${type}`);}
function relationFor(row,type){return(row.relations||[]).find((relation)=>relation.type===type)||null;}
function rowTypes(row){const types=new Set();if(row.primaryType&&PRIMARY_RHYME_TYPES.includes(row.primaryType))types.add(row.primaryType);else if(PRIMARY_RHYME_TYPES.includes(row.type))types.add(row.type);for(const type of row.relationTypes||[])if(SOUND_RELATION_TYPES.includes(type))types.add(type);return RHYME_TYPES.filter((type)=>types.has(type));}
function matchesType(row,type){return rowTypes(row).includes(type);}
function displayScore(row,type){return SOUND_RELATION_TYPES.includes(type)?Number(relationFor(row,type)?.score||0):Number(row.score||0);}

function applyLanguage(){document.documentElement.lang=state.lang;document.title=t('title');$('#searchInput').placeholder=t('searchPlaceholder');$('#searchInput').setAttribute('aria-label',t('searchPlaceholder'));$('#searchButton').textContent=t('search');$('[data-i18n]').forEach((node)=>{node.textContent=t(node.dataset.i18n);});$('[data-i18n-option]').forEach((node)=>{node.textContent=t(node.dataset.i18nOption);});$('.basis-option').forEach((button)=>button.classList.toggle('active',button.dataset.basis===state.basis));if(state.data)render();}
function compareRecommended(a,b){if(a.resultKind!==b.resultKind)return a.resultKind==='word'?-1:1;const ar=Number(a.channelRank||a.writerRank||a.diversifiedPageRank||0),br=Number(b.channelRank||b.writerRank||b.diversifiedPageRank||0);if(ar&&br&&ar!==br)return ar-br;if(Number.isFinite(a.writerRank)&&Number.isFinite(b.writerRank))return a.writerRank-b.writerRank;return Number(a.rhymeTier??99)-Number(b.rhymeTier??99)||Number(a.syllableDistance||0)-Number(b.syllableDistance||0)||(a.usageRank==null)-(b.usageRank==null)||Number(a.usageRank??Number.MAX_SAFE_INTEGER)-Number(b.usageRank??Number.MAX_SAFE_INTEGER)||Number(b.score||0)-Number(a.score||0)||String(a.word||'').localeCompare(String(b.word||''),'de');}
function compareForDisplayType(a,b,type){if(SOUND_RELATION_TYPES.includes(type)){const ar=relationFor(a,type),br=relationFor(b,type);return(Number(ar?.strength!=='strong')-Number(br?.strength!=='strong'))||displayScore(b,type)-displayScore(a,type)||a.syllableDistance-b.syllableDistance||(a.usageRank==null)-(b.usageRank==null)||(a.usageRank??Number.MAX_SAFE_INTEGER)-(b.usageRank??Number.MAX_SAFE_INTEGER)||b.score-a.score;}return compareRecommended(a,b);}
function filteredResults(){if(!state.data)return[];const querySyllables=Number(state.data.query?.syllableCount||0),type=$('#typeFilter').value,syllable=$('#syllableFilter').value,scope=$('#scopeFilter').value;let rows=state.data.results.filter((row)=>{if(scope==='words'&&row.resultKind==='phrase')return false;if(scope==='phrases'&&row.resultKind!=='phrase')return false;if(type!=='all'&&!matchesType(row,type))return false;const distance=querySyllables?Math.abs(Number(row.syllableCount||0)-querySyllables):0;if(syllable==='same'&&distance!==0)return false;if(syllable==='near'&&distance>1)return false;return true;});const mode=$('#sortMode').value;rows=[...rows].sort((a,b)=>{if(a.resultKind!==b.resultKind)return a.resultKind==='word'?-1:1;if(type!=='all'&&mode==='recommended')return compareForDisplayType(a,b,type);if(mode==='common'){if(a.resultKind==='phrase')return Number(b.usageCount||0)-Number(a.usageCount||0)||compareRecommended(a,b);return(a.usageRank==null)-(b.usageRank==null)||Number(a.usageRank??Number.MAX_SAFE_INTEGER)-Number(b.usageRank??Number.MAX_SAFE_INTEGER)||compareRecommended(a,b);}if(mode==='closest')return(type!=='all'?displayScore(b,type)-displayScore(a,type):Number(b.score||0)-Number(a.score||0))||compareRecommended(a,b);if(mode==='alpha')return String(a.word||'').localeCompare(String(b.word||''),state.lang==='de'?'de':'en',{sensitivity:'base'});return compareRecommended(a,b);});return rows;}
function interleaveByType(rows){if(state.data?.schema==='rhymelab-unified-writer-v1')return rows;if(String(state.data?.rankingPolicy||'').startsWith('deterministic_writer_utility_'))return rows;if($('#typeFilter').value!=='all')return rows;const buckets=RHYME_TYPES.map((type)=>rows.filter((row)=>matchesType(row,type)).sort((a,b)=>compareForDisplayType(a,b,type))).filter((bucket)=>bucket.length);if(buckets.length<=1)return rows;const output=[],seen=new Set();for(let index=0;output.length<rows.length;index+=1){let added=false;for(const bucket of buckets){const row=bucket[index];if(row&&!seen.has(row.normalized)){seen.add(row.normalized);output.push(row);added=true;}}if(!added&&buckets.every((bucket)=>index>=bucket.length))break;}for(const row of rows)if(!seen.has(row.normalized)){seen.add(row.normalized);output.push(row);}return output;}
function rhymeAnalysisHtml(result,displayType=null){if(!result)return'';const component=(key,label)=>{const value=result.components?.[key];if(value==null)return'';return`<div class="analysis-metric"><span>${label}</span><strong>${Math.round(value*100)}%</strong></div>`;};const primary=result.primaryType||((PRIMARY_RHYME_TYPES.includes(result.type))?result.type:null);const relations=(result.relations||[]).map((relation)=>`<span class="badge ${esc(relation.type)}${displayType===relation.type?' active-relation':''}">${esc(typeLabel(relation.type))} · ${esc(t(relation.strength==='strong'?'relationStrong':'relationPartial'))} · ${Math.round(relation.score*100)}%</span>`).join('');return`<div class="rhyme-analysis"><h3>${t('rhymeAnalysis')}</h3><div class="analysis-summary"><div><span class="meta-label">${t('primaryRhyme')}</span><strong>${esc(primary?typeLabel(primary):t('relationOnly'))}</strong></div><div><span class="meta-label">${t('matchScore')}</span><strong>${primary?`${Math.round(result.score*100)}%`:'—'}</strong></div></div>${relations?`<div class="relation-summary"><span class="meta-label">${t('soundRelations')}</span><div>${relations}</div></div>`:''}<div class="analysis-grid">${component('vowel',t('vowelFit'))}${component('coda',t('codaFit'))}${component('stress',t('stressFit'))}${component('syllable',t('syllableFit'))}${component('consonance',t('consonanceFit'))}${component('onset',t('onsetFit'))}</div></div>`;}
function renderWordPanel(query,rhymeResult=null,displayType=null){const pronunciations=query.pronunciations||[],preferred=pronunciations.find((p)=>p.preferred)||pronunciations[0],layer=query.lexiconLayer==='modern'?t('modern'):t('dictionary');const pronunciationHtml=pronunciations.slice(0,8).map((p)=>{const detail=[p.preferred?t('standardLabel'):t('alternate'),p.locale?localeLabel(p.locale):null,p.register?registerLabel(p.register):null,p.dialect?dialectLabel(p.dialect):null].filter(Boolean).join(' · ');return`<div class="pronunciation-item"><code>/${esc(p.ipa)}/</code><small>${esc(detail)}</small></div>`;}).join('');const tags=Array.isArray(query.lexicalTags)?query.lexicalTags:[],tagHtml=tags.length?`<div class="lexical-tags"><span class="meta-label">${t('lexicalTags')}</span><div>${tags.map((tag)=>`<span title="${esc(tag)}">${esc(lexicalTagLabel(tag))}</span>`).join('')}</div></div>`:'',source=sourceLabel(preferred?.source),grammaticalLabel=partOfSpeechLabel(query.partOfSpeech)||entityLabel(query.entityKind)||'—';$('#wordPanel').innerHTML=`<div class="word-heading"><div><h2>${esc(query.surface)}</h2><div class="ipa">/${esc(query.preferredIpa||preferred?.ipa||'')}/</div></div><div class="layer-badges"><span class="layer-badge ${query.lexiconLayer==='modern'?'modern':''}">${esc(layer)}</span>${query.historical?`<span class="layer-badge historical">${t('historical')}</span>`:''}</div></div><div class="meta-grid"><div class="meta-item"><span class="meta-label">${t('syllableCount')}</span><span class="meta-value">${esc(query.syllableCount??t('unknown'))}</span></div><div class="meta-item"><span class="meta-label">${t('primaryStress')}</span><span class="meta-value">${esc(query.primaryStressSyllable??t('unknown'))}</span></div><div class="meta-item"><span class="meta-label">${t('usageRank')}</span><span class="meta-value">${query.usageRank?`#${number(query.usageRank)}`:t('unranked')}</span></div><div class="meta-item"><span class="meta-label">${t('corpusCount')}</span><span class="meta-value">${query.usageCount!=null?number(query.usageCount):'—'}</span></div><div class="meta-item"><span class="meta-label">${t('partOfSpeech')}</span><span class="meta-value">${esc(grammaticalLabel)}</span></div><div class="meta-item"><span class="meta-label">${t('lemma')}</span><span class="meta-value">${esc(query.lemma||'—')}</span></div><div class="meta-item meta-wide"><span class="meta-label">${t('source')}</span><span class="meta-value source-value">${esc(source)}</span></div></div>${rhymeAnalysisHtml(rhymeResult,displayType)}${tagHtml}<div class="pronunciation-list"><h3>${t('variants')}</h3>${pronunciationHtml||'—'}</div>`;}
function renderPhrasePanel(query,rhymeResult=null,detail=null,displayType=null){const surface=detail?.canonical||query.surface||query.word||'',ipa=detail?.ipa||query.preferredIpa||query.ipa||'',phraseTypes=detail?.phraseTypes||query.phraseTypes||[],attestation=detail?.attestations?.[0]||null,source=attestation?.name?[attestation.name,attestation.license_id].filter(Boolean).join(' · '):(query.pronunciationProvenance||'RhymeLab Phrase/Mosaic'),occurrences=rhymeResult?.usageCount??(detail?.leipzig||[]).reduce((sum,row)=>sum+Number(row.occurrence_count||0),0);$('#wordPanel').innerHTML=`<div class="word-heading"><div><h2>${esc(surface)}</h2><div class="ipa">/${esc(ipa)}/</div></div><div class="layer-badges"><span class="layer-badge modern">${t('phrase')}</span>${query.historical||detail?.historicalState==='historical_only'?\`<span class="layer-badge historical">${t('historical')}</span>\`:''}</div></div><div class="meta-grid"><div class="meta-item"><span class="meta-label">${t('syllableCount')}</span><span class="meta-value">${esc(detail?.syllableCount??query.syllableCount??'—')}</span></div><div class="meta-item"><span class="meta-label">${t('partOfSpeech')}</span><span class="meta-value">${t('phrase')}</span></div><div class="meta-item"><span class="meta-label">Phrase types</span><span class="meta-value">${esc(phraseTypes.length?phraseTypes.map(humanize).join(', '):'—')}</span></div><div class="meta-item"><span class="meta-label">Leipzig</span><span class="meta-value">${occurrences?number(occurrences):'—'}</span></div>${rhymeResult?.crossedWordBoundaries!=null?\`<div class="meta-item"><span class="meta-label">Word boundaries</span><span class="meta-value">${esc(rhymeResult.crossedWordBoundaries)}</span></div>\`:''}<div class="meta-item meta-wide"><span class="meta-label">${t('source')}</span><span class="meta-value source-value">${esc(source)}</span></div></div>${rhymeAnalysisHtml(rhymeResult,displayType)}`;}
function resultRow(row,displayType){const isPhrase=row.resultKind==='phrase',usage=isPhrase?(row.usageCount?number(row.usageCount):'—'):(row.usageRank?`#${number(row.usageRank)}`:'—'),usageSub=isPhrase?'Leipzig':(row.usageCount!=null?number(row.usageCount):t('unranked')),score=displayScore(row,displayType),key=`${row.resultKind||'word'}:${row.resultId||row.windowId||row.normalized||row.word}`;return`<div class="result-row ${isPhrase?'phrase-row':''}" data-result-key="${esc(key)}" data-display-type="${esc(displayType)}" tabindex="0" aria-label="${esc(`${t('inspectWord')} ${row.word}`)}"><div class="result-word"><div class="result-title-line"><strong>${esc(row.word)}</strong><span class="kind-chip ${isPhrase?'phrase':'word'}">${isPhrase?t('phrase'):t('word')}</span></div><div class="sub"><code>${isPhrase&&row.ipaKind==='matched_mosaic_span'?'span: ':''}/${esc(row.ipa||'')}/</code>${row.historical?`<span class="historical-text">${t('historicalEntity')}</span>`:''}</div></div><div class="type-col"><span class="badge ${esc(displayType)}">${esc(typeLabel(displayType))}</span></div><div class="syllable-col metric">${esc(row.syllableCount??'—')}<span class="muted">${t('syllableShort')}</span></div><div class="usage-col metric">${usage}<span class="muted">${esc(usageSub)}</span></div><div class="score">${Math.round(score*100)}%</div></div>`;}
function section(type,rows,totalCount){return`<section class="result-section ${esc(type)}"><div class="result-section-header"><span class="type-dot"></span><h2>${esc(typeLabel(type))}</h2><span class="count">${totalCount}</span></div>${rows.map((row)=>resultRow(row,type)).join('')}</section>`;}
function setupInfiniteScroll(hasMore){state.scrollObserver?.disconnect();state.scrollObserver=null;const sentinel=$('#scrollSentinel');sentinel.classList.toggle('hidden',!hasMore);if(!hasMore)return;if(!('IntersectionObserver'in window)){state.visibleCount=Number.MAX_SAFE_INTEGER;render();return;}state.scrollObserver=new IntersectionObserver((entries)=>{if(!entries.some((entry)=>entry.isIntersecting))return;state.visibleCount+=state.pageSize;render();},{rootMargin:'500px 0px'});state.scrollObserver.observe(sentinel);}
function render(){if(!state.data)return;if(!state.inspectedWord){if(state.data.query?.kind==='phrase')renderPhrasePanel(state.data.query);else renderWordPanel(state.data.query);}const rows=filteredResults(),ordered=interleaveByType(rows),words=ordered.filter((row)=>row.resultKind!=='phrase'),phrases=ordered.filter((row)=>row.resultKind==='phrase');$('#resultCount').textContent=`${number(rows.length)} ${rows.length===1?t('result'):t('results')} · ${number(words.length)} ${t('words')} · ${number(phrases.length)} ${t('phrases')}`;const block=(kind,label,items)=>items.length?`<div class="channel-block ${kind}"><div class="channel-header"><strong>${label}</strong><span>${number(items.length)}</span></div>${RHYME_TYPES.map((type)=>{const typed=items.filter((row)=>matchesType(row,type));return typed.length?section(type,typed,typed.length):'';}).join('')}</div>`:'';const html=block('word',t('words'),words)+block('phrase',t('phrases'),phrases);$('#results').innerHTML=html||`<div class="status">${t('noResults')}</div>`;setupInfiniteScroll(false);renderCapabilityNotice(state.data.warnings||[]);}
function resultByKey(key){return state.data?.results?.find((row)=>`${row.resultKind||'word'}:${row.resultId||row.windowId||row.normalized||row.word}`===key)||null;}
async function inspectResult(result,displayType=null){if(!result)return;const key=`${result.resultKind||'word'}:${result.resultId||result.windowId||result.normalized||result.word}`;if(!key||!state.data)return;state.inspectedWord=key;state.inspectedResult=result;state.inspectedType=displayType;const token=++state.detailRequest;if(result.resultKind==='phrase'){const cacheKey=`phrase:${result.phraseId||result.normalized}`,cached=state.wordCache.get(cacheKey);if(cached){if(token===state.detailRequest&&state.inspectedWord===key)renderPhrasePanel(result,result,cached,displayType);return;}if(!result.phraseId){renderPhrasePanel(result,result,null,displayType);return;}try{const response=await fetch(`/api/phrases/detail?id=${encodeURIComponent(result.phraseId)}`);if(!response.ok){renderPhrasePanel(result,result,null,displayType);return;}const detail=await response.json();state.wordCache.set(cacheKey,detail);if(token===state.detailRequest&&state.inspectedWord===key)renderPhrasePanel(result,result,detail,displayType);}catch{renderPhrasePanel(result,result,null,displayType);}return;}const wordKey=normalizeKey(result.normalized||result.word),cached=state.wordCache.get(wordKey);if(cached){if(token===state.detailRequest&&state.inspectedWord===key)renderWordPanel(cached,result,displayType);return;}try{const response=await fetch(`/api/word/${encodeURIComponent(result.word)}`);if(!response.ok)return;const detail=await response.json();state.wordCache.set(wordKey,detail);if(token===state.detailRequest&&state.inspectedWord===key)renderWordPanel(detail,result,displayType);}catch{}}
function restoreQueryPanel(){state.inspectedWord=null;state.inspectedResult=null;state.inspectedType=null;state.detailRequest+=1;if(state.data?.query?.kind==='phrase')renderPhrasePanel(state.data.query);else if(state.data?.query)renderWordPanel(state.data.query);}

function renderCapabilityNotice(warnings=[]){const node=$('#capabilityNotice');if(!node)return;const messages=[];if(state.basis==='en'&&state.capabilities?.languages?.en?.available===false)messages.push(t('englishUnavailable'));else if(state.basis==='both'&&state.capabilities?.languages?.en?.available===false)messages.push(t('bothPartial'));for(const warning of warnings||[])if(warning?.message&&!messages.includes(warning.message))messages.push(warning.message);node.textContent=messages.join(' ');node.classList.toggle('hidden',messages.length===0);}
async function loadCapabilities(){try{const response=await fetch('/api/health');if(!response.ok)return;const health=await response.json();state.capabilities=health.unified_writer||null;$$('.basis-option').forEach((button)=>{const unavailable=button.dataset.basis==='en'&&state.capabilities?.languages?.en?.available===false;button.classList.toggle('unavailable',unavailable);if(unavailable)button.title=t('englishUnavailable');});renderCapabilityNotice();}catch{}}
async function search(word){state.query=word.trim();if(!state.query)return;$('#emptyState').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#loading').classList.remove('hidden');$('#error').classList.add('hidden');$('#results').innerHTML='';state.visibleCount=state.pageSize;state.inspectedWord=null;state.inspectedResult=null;state.inspectedType=null;state.detailRequest+=1;state.scrollObserver?.disconnect();try{const requestedType=$('#typeFilter').value,params=new URLSearchParams({q:state.query,language:state.basis,scope:$('#scopeFilter').value,word_limit:'250',word_pool:'800',phrase_limit:'250',phrase_pool:'512',phrase_per_channel:'128',variants:$('#variantMode').value,historical:$('#historicalMode').checked?'all':'current',type:requestedType}),response=await fetch(`/api/writer?${params}`),data=await response.json();if(!response.ok){const warning=(data.warnings||[]).map((entry)=>entry.message).filter(Boolean).join(' ');throw new Error(response.status===404?t('notFound'):(warning||data.error||data.status||'Request failed'));}state.data=data;state.capabilities=data.capabilities||state.capabilities;if(data.query?.kind==='word')state.wordCache.set(normalizeKey(data.query?.surface||state.query),data.query);const url=new URL(location.href);url.searchParams.set('q',state.query);url.searchParams.set('lang',state.basis);url.searchParams.set('scope',$('#scopeFilter').value);history.replaceState(null,'',url);render();}catch(error){state.data=null;$('#wordPanel').innerHTML='';$('#scrollSentinel').classList.add('hidden');$('#error').textContent=error.message;$('#error').classList.remove('hidden');renderCapabilityNotice();}finally{$('#loading').classList.add('hidden');}}

$('#searchForm').addEventListener('submit',(event)=>{event.preventDefault();search($('#searchInput').value);});
$$('.basis-option').forEach((button)=>button.addEventListener('click',()=>{state.basis=['de','en','both'].includes(button.dataset.basis)?button.dataset.basis:'de';localStorage.setItem('rhymelab.searchBasis',state.basis);applyLanguage();renderCapabilityNotice();if(state.query)search(state.query);}));
['scopeFilter','typeFilter','variantMode'].forEach((id)=>$('#'+id).addEventListener('change',()=>{if(state.query)search(state.query);else renderCapabilityNotice();}));
['syllableFilter','sortMode'].forEach((id)=>$('#'+id).addEventListener('change',()=>{state.visibleCount=state.pageSize;if(state.data)render();}));
$('#historicalMode').addEventListener('change',()=>{if(state.query)search(state.query);});
$('#results').addEventListener('pointerover',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;inspectResult(resultByKey(row.dataset.resultKey),row.dataset.displayType);});
$('#results').addEventListener('pointerout',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;restoreQueryPanel();});
$('#results').addEventListener('focusin',(event)=>{const row=event.target.closest('.result-row');if(row)inspectResult(resultByKey(row.dataset.resultKey),row.dataset.displayType);});
$('#results').addEventListener('focusout',(event)=>{const row=event.target.closest('.result-row');if(!row||row.contains(event.relatedTarget))return;restoreQueryPanel();});
applyLanguage();
const initialUrl=new URL(location.href),initialBasis=initialUrl.searchParams.get('lang'),initialScope=initialUrl.searchParams.get('scope');if(['de','en','both'].includes(initialBasis))state.basis=initialBasis;if(['all','words','phrases'].includes(initialScope))$('#scopeFilter').value=initialScope;applyLanguage();loadCapabilities();
const initial=initialUrl.searchParams.get('q');
if(initial){$('#searchInput').value=initial;search(initial);}
