const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
const T={en:{headline:'Browse phraseology and register evidence.',intro:'Inspect Wiktionary phrase records, Leipzig corpus evidence and modern register corpora without changing the Writer ranking.',phrasesTab:'Phrase catalog',corpusTab:'RUEG corpus units',searchPhrase:'Search phrase',type:'Type',leipzig:'Leipzig evidence',register:'Register evidence',history:'Vocabulary',search:'Search',more:'Load more',selectPhrase:'Select a phrase to inspect evidence.',searchCorpus:'Search RUEG text',mode:'Mode',formality:'Formality',noResults:'No results.',unavailable:'RUEG units are not imported yet. Run npm run phrase:register:rueg:bootstrap.',results:'results',tokens:'tokens',source:'Source',styles:'Style tags',categories:'Categories',usage:'Leipzig usage',registerEvidence:'Register evidence',examples:'RUEG examples',dipl:'Diplomatic',norm:'Normalized'},de:{headline:'Phraseologie und Register-Evidenz durchsuchen.',intro:'Wiktionary-Phrasen, Leipzig-Korpusbelege und moderne Registerkorpora lokal prüfen – ohne das Writer-Ranking zu verändern.',phrasesTab:'Phrasenkatalog',corpusTab:'RUEG-Korpuseinheiten',searchPhrase:'Phrase suchen',type:'Typ',leipzig:'Leipzig-Evidenz',register:'Register-Evidenz',history:'Wortschatz',search:'Suchen',more:'Mehr laden',selectPhrase:'Phrase auswählen, um Evidenz zu prüfen.',searchCorpus:'RUEG-Text suchen',mode:'Modus',formality:'Formalität',noResults:'Keine Ergebnisse.',unavailable:'RUEG-Einheiten sind noch nicht importiert. Führe npm run phrase:register:rueg:bootstrap aus.',results:'Ergebnisse',tokens:'Tokens',source:'Quelle',styles:'Stil-Tags',categories:'Kategorien',usage:'Leipzig-Nutzung',registerEvidence:'Register-Evidenz',examples:'RUEG-Beispiele',dipl:'Diplomatisch',norm:'Normalisiert'}};
const state={lang:localStorage.getItem('rhymelab.language')==='de'?'de':'en',phraseOffset:0,corpusOffset:0,phraseData:null,corpusData:null};
const t=(k)=>T[state.lang][k]||T.en[k]||k,esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v)=>Number(v||0).toLocaleString(state.lang==='de'?'de-DE':'en-US');
function applyLang(){document.documentElement.lang=state.lang;$$('[data-t]').forEach(n=>n.textContent=t(n.dataset.t));$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));renderStats(window.__stats);}
function tags(values,cls=''){return(values||[]).map(v=>`<span class="tag ${cls}">${esc(v)}</span>`).join('');}
async function api(path){const r=await fetch(path),data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
function showError(error){$('#error').textContent=error?.message||String(error);$('#error').classList.remove('hidden');}function clearError(){$('#error').classList.add('hidden');}
function renderStats(s){if(!s)return;$('#stats').innerHTML=`<div><strong>${num(s.phrases)}</strong><span>Phrases</span></div><div><strong>${num(s.leipzigMatched)}</strong><span>Leipzig</span></div><div><strong>${num(s.registerMatchedPhrases)}</strong><span>Register</span></div><div><strong>${num(s.ruegUnits)}</strong><span>RUEG CUs</span></div>`;}
async function loadStats(){try{window.__stats=await api('/api/phrases/stats');renderStats(window.__stats);}catch(e){showError(e);}}
function phraseParams(){return new URLSearchParams({q:$('#phraseQ').value,type:$('#phraseType').value,evidence:$('#evidence').value,register:$('#register').value,historical:$('#history').value,limit:'50',offset:String(state.phraseOffset)});}
function phraseCard(row){return`<button class="phrase-card" data-id="${esc(row.phrase_id)}"><div><strong>${esc(row.canonical)}</strong><div class="tagline">${tags(row.phraseTypes)}${row.historical_state==='historical_only'?'<span class="tag historical">historical</span>':''}</div></div><div class="evidence"><span><b>${num(row.leipzig_corpora)}</b> Leipzig</span><span><b>${num(row.register_evidence_rows)}</b> Register</span><span><b>${num(row.token_count)}</b> ${t('tokens')}</span></div></button>`;}
async function searchPhrases(reset=true){clearError();if(reset){state.phraseOffset=0;$('#phraseResults').innerHTML='';}try{const data=await api('/api/phrases/search?'+phraseParams());state.phraseData=data;$('#phraseSummary').textContent=`${num(data.total)} ${t('results')}`;$('#phraseResults').insertAdjacentHTML('beforeend',data.results.map(phraseCard).join('')||(!state.phraseOffset?`<div class="empty">${t('noResults')}</div>`:''));state.phraseOffset+=data.results.length;$('#phraseMore').classList.toggle('hidden',state.phraseOffset>=data.total);}catch(e){showError(e);}}
function evidenceBlock(title,rows,render){if(!rows?.length)return'';return`<section class="detail-section"><h3>${esc(title)}</h3>${rows.map(render).join('')}</section>`;}
async function inspectPhrase(id){clearError();try{const p=await api('/api/phrase/'+encodeURIComponent(id));const source=evidenceBlock(t('source'),p.attestations,(a)=>`<div class="evidence-row"><div><b>${esc(a.source_name)}</b> · ${esc(a.source_pos||'—')} · ${esc(a.license_id||'')}</div><div>${tags(a.styleTags,'style')} ${tags(a.phraseTypes)}</div>${a.categories?.length?`<small>${esc(a.categories.slice(0,8).join(' · '))}</small>`:''}</div>`);const usage=evidenceBlock(t('usage'),p.usage,(u)=>`<div class="evidence-row"><b>${esc(u.snapshot_label)}</b><span>${num(u.occurrence_count)} hits · ${Number(u.per_million_tokens).toFixed(2)}/M tokens</span></div>`);const reg=evidenceBlock(t('registerEvidence'),p.registerEvidence,(r)=>`<div class="evidence-row"><b>${esc(r.snapshot_label)}</b><span>${esc(r.policy)} · ${num(r.occurrence_count)} hits</span><div>${tags(r.registerTags,'register')}</div></div>`);const samples=evidenceBlock(t('examples'),p.registerSamples,(r)=>`<div class="sample"><div class="sample-meta">${esc(r.subcorpus)} · ${esc(r.formality||'—')} · ${esc(r.mode||'—')} · ${esc(r.policy)}</div><p><span>${t('dipl')}</span>${esc(r.dipl_text)}</p><p><span>${t('norm')}</span>${esc(r.norm_text||'—')}</p></div>`);$('#phraseDetail').innerHTML=`<div class="detail-head"><p class="mono">${esc(p.phrase_id)}</p><h2>${esc(p.canonical)}</h2><div>${tags(p.phraseTypes)}</div><p>${p.tokens.map(x=>esc(x.surface)).join(' · ')}</p></div>${source}${usage}${reg}${samples}`;}catch(e){showError(e);}}
function corpusParams(){return new URLSearchParams({q:$('#corpusQ').value,layer:$('#layer').value,subcorpus:$('#subcorpus').value,mode:$('#mode').value,formality:$('#formality').value,limit:'50',offset:String(state.corpusOffset)});}
function corpusCard(row){const lang=(row.languageValues||[]).join(', ')||'—',ratio=row.german_token_ratio==null?'—':`${Math.round(row.german_token_ratio*100)}%`;return`<article class="corpus-card"><div class="corpus-meta"><b>${esc(row.subcorpus)}</b><span>${esc(row.formality||'—')}</span><span>${esc(row.mode||'—')}</span><span>lang ${esc(lang)} · DE ${ratio}</span><span>${num(row.matched_phrases)} phrase matches</span></div><div class="layers"><div><span>dipl</span><p>${esc(row.dipl_text)}</p></div><div><span>norm</span><p>${esc(row.norm_text||'—')}</p></div></div><small>${esc(row.source_record_id)} · CU ${num(row.unit_index+1)}</small></article>`;}
async function searchCorpus(reset=true){clearError();if(reset){state.corpusOffset=0;$('#corpusResults').innerHTML='';}try{const data=await api('/api/register/search?'+corpusParams());state.corpusData=data;if(!data.available){$('#corpusSummary').textContent=t('unavaile');$('#corpusResults').innerHTML='';$('#corpusMore').classList.add('hidden');return;}$('#corpusSummary').textContent=`${num(data.total)} ${t('results')}`;$('#corpusResults').insertAdjacentHTML('beforeend',data.results.map(corpusCard).join('')||(!state.corpusOffset?`<div class="empty">${t('noResults')}</div>`:''));state.corpusOffset+=data.results.length;$('#corpusMore').classList.toggle('hidden',state.corpusOffset>=data.total);}catch(e){showError(e);}}
$('#phraseForm').addEventListener('submit',e=>{e.preventDefault();searchPhrases(true);});$('#corpusForm').addEventListener('submit',e=>{e.preventDefault();searchCorpus(true);});$('#phraseMore').addEventListener('click',()=>searchPhrases(false));$('#corpusMore').addEventListener('click',()=>searchCorpus(false));$('#phraseResults').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)inspectPhrase(b.dataset.id);});$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#phrasesPane').classList.toggle('hidden',b.dataset.tab!=='phrases');$('#corpusPane').classList.toggle('hidden',b.dataset.tab!=='corpus');if(b.dataset.tab==='corpus'&&!state.corpusData)searchCorpus(true);}));$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang==='de'?'de':'en';localStorage.setItem('rhymelab.language',state.lang);applyLang();}));
applyLang();loadStats();searchPhrases(true);
