const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v)=>Number(v||0).toLocaleString('de-DE');
async function api(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data}
function badge(text,cls=''){return '<span class="badge '+cls+'">'+esc(text)+'</span>'}
function showStatus(text){$('#status').textContent=text;$('#status').classList.toggle('hidden',!text)}
function renderStats(s){if(!s)return;$('#stats').innerHTML=[
  ['Phrasen',s.phrases],['Leipzig',s.leipzig?.matchedPhrases],['Register',s.register?.matchedPhrases??0],
  ['IPA ready',s.pronunciation?.readyPhrases??0],['IPA tokens',s.pronunciation?.resolvedTokens??0]
].map(([label,value])=>'<div class="stat"><strong>'+num(value)+'</strong><span>'+esc(label)+'</span></div>').join('')}
async function loadMeta(){try{renderStats(await api('/api/phrases/stats'))}catch(e){showStatus(e.message)}}
function phraseRow(p){const types=(p.phraseTypes||[]).map(t=>badge(t,t)).join('');const ipa=p.pronunciationReady?'<div class="ipa-line">/'+esc(p.ipa)+'/ · '+p.syllableCount+' Silben · Stress '+esc(p.stressPattern)+'</div>':'';return '<article class="phrase-row" tabindex="0" data-id="'+esc(p.phraseId)+'"><div class="phrase-head"><strong>'+esc(p.canonical)+'</strong><div class="badges">'+types+(p.pronunciationReady?badge('IPA','reg'):'')+(p.historicalState==='historical_only'?badge('historisch','hist'):'')+'</div></div>'+ipa+'<div class="metrics"><span>'+p.tokenCount+' tokens</span><span>Leipzig '+p.leipzigCorpusCount+'/3 · '+num(p.leipzigOccurrences)+'</span><span>Register '+num(p.registerOccurrences)+'</span></div></article>'}
async function search(){showStatus('Lade…');try{const p=new URLSearchParams({q:$('#query').value.trim(),type:$('#typeFilter').value,evidence:$('#evidenceFilter').value,limit:$('#phraseLimit').value});if($('#historicalFilter').checked)p.set('historical','all');const data=await api('/api/phrases/search?'+p);$('#results').innerHTML=data.results.length?data.results.map(phraseRow).join(''):'<div class="empty">Keine Treffer.</div>';showStatus('')}catch(e){showStatus(e.message)}}
function evidenceBlock(title,value,cls=''){return '<div class="evidence '+cls+'"><strong>'+esc(title)+'</strong><div>'+value+'</div></div>'}
async function detail(id){try{const d=await api('/api/phrases/detail?id='+encodeURIComponent(id));let html='<h2>'+esc(d.canonical)+'</h2><div class="badges">'+(d.phraseTypes||[]).map(t=>badge(t,t)).join('')+(d.pronunciationReady?badge('IPA ready','reg'):'')+'</div><div class="detail-grid"><div class="detail-cell"><span>Tokens</span><strong>'+d.tokenCount+'</strong></div><div class="detail-cell"><span>History</span><strong>'+esc(d.historicalState)+'</strong></div></div>';html+='<h3>Pronunciation · 11C1</h3>';if(d.pronunciation){const p=d.pronunciation;html+='<div class="pron-card"><div class="ipa-main">/'+esc(p.ipa)+'/</div><div class="metrics"><span>'+p.syllable_count+' Silben</span><span>Stress '+esc(p.stress_pattern)+'</span><span>Boundaries '+esc((p.wordBoundarySyllablePositions||[]).join(', ')||'—')+'</span></div>'+(p.tokens||[]).map(t=>'<div class="pron-token"><b>'+esc(t.writer_surface)+'</b><span>/'+esc(t.ipa)+'/</span><small>phon '+t.phoneme_start+'–'+t.phoneme_end+' · syll '+t.syllable_start+'–'+t.syllable_end+(t.available_pronunciations>1?' · '+t.available_pronunciations+' variants':'')+'</small></div>').join('')+'</div>';}else if(d.pronunciationResolutions?.length){html+='<div class="empty">Noch keine vollständige Phrase-Aussprache.</div>'+d.pronunciationResolutions.map(x=>'<div class="evidence"><strong>'+esc(x.normalized)+'</strong><div>'+esc(x.status)+(x.ipa?' · /'+esc(x.ipa)+'/':'')+'</div></div>').join('');}else{html+='<div class="empty">11C1 noch nicht materialisiert.</div>';}html+='<h3>Source attestations</h3>'+(d.attestations.length?d.attestations.map(a=>evidenceBlock(a.name+' · '+(a.source_pos||'—'),'<div class="badges">'+(a.style_tags||[]).map(x=>badge(x)).join('')+'</div>')).join(''):'<div class="empty">Keine.</div>');html+='<h3>Leipzig</h3>'+(d.leipzig.length?d.leipzig.map(x=>evidenceBlock(x.snapshot_label,num(x.occurrence_count)+' occurrences · '+Number(x.per_million_tokens).toFixed(2)+'/M tokens','leipzig')).join(''):'<div class="empty">Keine Leipzig-Evidenz.</div>');html+='<h3>Register evidence</h3>'+(d.register.length?d.register.map(x=>evidenceBlock(x.snapshot_label+' · '+x.policy,num(x.occurrence_count)+' occurrences','register')).join(''):'<div class="empty">Keine Register-Evidenz.</div>');$('#detail').innerHTML=html}catch(e){showStatus(e.message)}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();search()});
['#typeFilter','#evidenceFilter','#historicalFilter','#phraseLimit'].forEach(id=>$(id).addEventListener('change',search));
$('#results').addEventListener('click',e=>{const row=e.target.closest('.phrase-row');if(row)detail(row.dataset.id)});
$('#results').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.phrase-row')){e.preventDefault();detail(e.target.closest('.phrase-row').dataset.id)}});
loadMeta().then(search);
